# exclude vendored files and patches
exclude: '^(COPYING\.LESSER|subprojects/.*)$'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        name: Modernize python code
        args: ["--py38-plus"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Reorder python imports with isort

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: Format python code with black

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Lint python code with flake8
        additional_dependencies: [flake8-bugbear, Flake8-pyproject]

  - repo: meta
    hooks:
      # - id: check-hooks-apply
      - id: check-useless-excludes
