# Action to convert a Docker image ref of the builder container to
# a repo and image digest

name: Find builder container digest
description: Get repo and image digest of the OpenSlide builder container
inputs:
  builder_image:
    description: |
      Docker image reference of the builder container, or "windows" or "linux"
    required: false
    type: string
outputs:
  builder_repo_and_digest:
    description: Docker repo and image digest of the builder container
    value: ${{ steps.find.outputs.builder_repo_and_digest }}

runs:
  using: composite
  steps:
    - id: find
      shell: bash
      run: |
        repo=$(cut -f1 -d: <<<"${{ inputs.builder_image }}")
        case "$repo" in
        windows|"") repo=ghcr.io/openslide/winbuild-builder ;;
        linux) repo=ghcr.io/openslide/linux-builder ;;
        esac
        label=$(cut -f2 -d: -s <<<"${{ inputs.builder_image }}")
        label="${label:-latest}"
        digest=$(skopeo inspect "docker://${repo}:${label}" | jq -r .Digest)
        ref="${repo}@${digest}"
        echo "Builder container:"
        echo "${ref}"
        echo "builder_repo_and_digest=${ref}" >> $GITHUB_OUTPUT
