# Build stable releases on push to openslide-winbuild main.
# Nightly builds from Git are handled elsewhere.

name: Build main

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      linux_builder_repo_and_digest: ${{ steps.find-linux.outputs.builder_repo_and_digest }}
      pkgver: ${{ steps.params.outputs.pkgver }}
      windows_builder_repo_and_digest: ${{ steps.find-windows.outputs.builder_repo_and_digest }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Find Linux builder container digest
        id: find-linux
        uses: ./.github/find-container-digest
        with:
          builder_image: linux
      - name: Find Windows builder container digest
        id: find-windows
        uses: ./.github/find-container-digest
        with:
          builder_image: windows
      - name: Calculate parameters
        id: params
        run: echo "pkgver=main-$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_OUTPUT

  stable:
    name: Stable
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      linux_builder_repo_and_digest: ${{ needs.setup.outputs.linux_builder_repo_and_digest }}
      macos_enable: true
      openslide_winbuild_repo: ${{ github.repository }}
      openslide_winbuild_ref: ${{ github.ref }}
      pkgver: ${{ needs.setup.outputs.pkgver }}
      windows_builder_repo_and_digest: ${{ needs.setup.outputs.windows_builder_repo_and_digest }}
