# PR CI workflow for openslide-winbuild

name: Build

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest
    outputs:
      linux_builder_repo_and_digest: ${{ steps.find-linux.outputs.builder_repo_and_digest }}
      pkgver: ${{ steps.params.outputs.pkgver }}
      windows_builder_repo_and_digest: ${{ steps.find-windows.outputs.builder_repo_and_digest }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Find Linux builder container digest
        id: find-linux
        uses: ./.github/find-container-digest
        with:
          builder_image: linux
      - name: Find Windows builder container digest
        id: find-windows
        uses: ./.github/find-container-digest
        with:
          builder_image: windows
      - name: Calculate parameters
        id: params
        run: echo "pkgver=pr-${{ github.event.number }}.${{ github.run_number }}.${{ github.run_attempt }}-$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_OUTPUT

  stable:
    name: Stable
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      linux_builder_repo_and_digest: ${{ needs.setup.outputs.linux_builder_repo_and_digest }}
      openslide_winbuild_repo: ${{ github.repository }}
      openslide_winbuild_ref: ${{ github.ref }}
      pkgver: ${{ needs.setup.outputs.pkgver }}-stable
      windows_builder_repo_and_digest: ${{ needs.setup.outputs.windows_builder_repo_and_digest }}

  git:
    name: Git
    needs: setup
    uses: ./.github/workflows/build.yml
    with:
      linux_builder_repo_and_digest: ${{ needs.setup.outputs.linux_builder_repo_and_digest }}
      openslide_repo: openslide/openslide
      openslide_ref: main
      openslide_java_repo: openslide/openslide-java
      openslide_java_ref: main
      openslide_winbuild_repo: ${{ github.repository }}
      openslide_winbuild_ref: ${{ github.ref }}
      pkgver: ${{ needs.setup.outputs.pkgver }}-git
      werror: true
      windows_builder_repo_and_digest: ${{ needs.setup.outputs.windows_builder_repo_and_digest }}
